cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - 'packages/**'
  - 'examples/react/**'
  - 'examples/start/**'

allowBuilds:
  nx: true
  workerd: true
  esbuild: true
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@cloudflare/vite-plugin@1.54.4'
  - miniflare@5.20260903.0-alpha
  - wrangler@4.129.0
