/** The module name the written plugin is loaded under, inside the isolate. */
export const pluginModule = 'plugin.js'

/** The module name the host's own wrapper is loaded under. */
export const wrapperModule = 'compose-host.js'

/** The entrypoint the wrapper exposes, and the only thing the client calls. */
export const wrapperEntrypoint = 'ComposeHostedPlugin'

/** The Durable Object class exported when the wrapper runs as a facet. */
export const facetWrapperEntrypoint = 'ComposeHostedFacet'

/**
 * What every wrapper method answers with. An envelope rather than a throw: RPC
 * carries an exception's message but not its own properties, and the phase a
 * failure belongs to is the part the client has to keep.
 */
export interface WrapperResult {
  ok: boolean
  value?: unknown
  phase?: 'parse' | 'load' | 'setup' | 'call'
  message?: string
}

/**
 * The wrapper module: the Dynamic Worker's `mainModule`, generated by the host
 * and never written by anyone. It is the whole of what the isolate does beyond
 * the plugin's own module.
 *
 * It has three jobs and no others:
 *
 * - build `stubs` from `env`, so `stubs.<name>(input)` is one loopback call;
 * - run the written module's default export once, keeping the cleanup it
 *   returned;
 * - answer `setup`, `call` and `stop` from the client.
 *
 * The written module is imported dynamically so a syntax error or a throw while
 * it evaluates is caught here and reported with its phase, rather than taking
 * the whole isolate down before anything can name what happened.
 *
 * What the plugin can see is exactly `{ id, options, stubs }`. `env`, `ctx`,
 * the loader and the wrapper's own state are all closed over in this module and
 * never passed across (D6).
 */
export function wrapperSource(
  stubNames: ReadonlyArray<string>,
  stubMethods: Readonly<Record<string, ReadonlyArray<string>>> = {},
): string {
  return `import { WorkerEntrypoint } from 'cloudflare:workers'

const stubNames = ${JSON.stringify([...stubNames])}
const stubMethods = ${JSON.stringify(stubMethods)}

/** One capability object, built from the loopbacks and nothing else. */
function stubsFrom(env) {
  const stubs = Object.create(null)
  for (const name of stubNames) {
    const loopback = env[name]
    const call = async (input) => {
      const answer = await loopback.stubCall(input)
      if (!answer.ok) throw new Error(answer.message)
      return answer.value
    }
    const methods = stubMethods[name]
    if (methods) {
      const shaped = Object.create(null)
      for (const method of methods) {
        shaped[method] = (...args) => call({ method, args })
      }
      stubs[name] = Object.freeze(shaped)
    } else {
      stubs[name] = call
    }
  }
  return Object.freeze(stubs)
}

const failed = (phase, error) => ({
  ok: false,
  phase,
  message:
    error && typeof error.message === 'string' ? error.message : String(error),
})

class Tagged extends Error {
  constructor(phase, error) {
    super('tagged')
    this.result = failed(phase, error)
  }
}

/**
 * One run of the written module, keyed by the token the client minted for this
 * start. An isolate is cached by content (D2), so the same isolate serves a
 * restart of the same instance; keying the state by start rather than by
 * isolate is what makes a restart run setup again and register its cleanups
 * again, exactly as a cold isolate would.
 */
const runs = new Map()

/** Load the written module and run its setup, at most once per start. */
function ensure(env, props) {
  let run = runs.get(props.run)
  if (!run) {
    run = (async () => {
      let plugin
      try {
        plugin = await import('./${pluginModule}')
      } catch (error) {
        throw new Tagged(error && error.name === 'SyntaxError' ? 'parse' : 'load', error)
      }
      if (typeof plugin.default !== 'function') {
        throw new Tagged(
          'load',
          new Error('plugin source must export a default setup function'),
        )
      }
      let cleanup
      try {
        const result = await plugin.default({
          id: props.instanceId,
          options: props.options,
          stubs: stubsFrom(env),
        })
        if (typeof result === 'function') cleanup = result
      } catch (error) {
        throw new Tagged('setup', error)
      }
      return { plugin, cleanup }
    })()
    runs.set(props.run, run)
  }
  return run
}

export class ${wrapperEntrypoint} extends WorkerEntrypoint {
  async setup() {
    try {
      await ensure(this.env, this.ctx.props)
      return { ok: true }
    } catch (error) {
      return error instanceof Tagged ? error.result : failed('setup', error)
    }
  }

  async call(name, input) {
    let plugin
    try {
      ;({ plugin } = await ensure(this.env, this.ctx.props))
    } catch (error) {
      return error instanceof Tagged ? error.result : failed('setup', error)
    }
    const handler = plugin[name]
    if (typeof handler !== 'function') {
      return failed(
        'call',
        new Error('plugin source has no export named "' + name + '"'),
      )
    }
    try {
      return { ok: true, value: await handler(input) }
    } catch (error) {
      return failed('call', error)
    }
  }

  async stop() {
    const run = runs.get(this.ctx.props.run)
    runs.delete(this.ctx.props.run)
    if (!run) return { ok: true }
    try {
      const { cleanup } = await run
      await cleanup?.()
    } catch {
      // The isolate is going away; a cleanup that throws changes nothing.
    }
    return { ok: true }
  }
}
`
}

/**
 * The Dynamic Worker module used for a Durable Object facet. Storage is local
 * to the facet; every other granted stub is a loopback to the parent object.
 */
export function facetWrapperSource(
  stubNames: ReadonlyArray<string>,
  stubMethods: Readonly<Record<string, ReadonlyArray<string>>> = {},
): string {
  return `import { DurableObject } from 'cloudflare:workers'

const stubNames = ${JSON.stringify([...stubNames])}
const stubMethods = ${JSON.stringify(stubMethods)}
const dataPrefix = '\\0compose:data:'

const failed = (phase, error) => ({
  ok: false,
  phase,
  message:
    error && typeof error.message === 'string' ? error.message : String(error),
})

class Tagged extends Error {
  constructor(phase, error) {
    super('tagged')
    this.result = failed(phase, error)
  }
}

const key = (value) => {
  if (typeof value !== 'string') throw new Error('storage key must be a string')
  return value
}

function stubsFrom(ctx, env) {
  const stubs = Object.create(null)
  for (const name of stubNames) {
    if (name === 'storage' || name === 'schedule') continue
    const loopback = env[name]
    const call = async (input) => {
      const answer = await loopback.stubCall(input)
      if (!answer.ok) throw new Error(answer.message)
      return answer.value
    }
    const methods = stubMethods[name]
    if (methods) {
      const shaped = Object.create(null)
      for (const method of methods) {
        shaped[method] = (...args) => call({ method, args })
      }
      stubs[name] = Object.freeze(shaped)
    } else {
      stubs[name] = call
    }
  }
  if (stubNames.includes('storage')) {
    stubs.storage = Object.freeze({
      get: (name) => ctx.storage.get(dataPrefix + key(name)),
      set: (name, value) => ctx.storage.put(dataPrefix + key(name), value),
      delete: (name) => ctx.storage.delete(dataPrefix + key(name)),
      list: async (prefix = '') => {
        const values = await ctx.storage.list({ prefix: dataPrefix + key(prefix) })
        const result = {}
        for (const [name, value] of values) {
          result[name.slice(dataPrefix.length)] = value
        }
        return result
      },
    })
  }
  if (stubNames.includes('schedule')) {
    const loopback = env.schedule
    const call = async (input) => {
      const answer = await loopback.stubCall(input)
      if (!answer.ok) throw new Error(answer.message)
      return answer.value
    }
    stubs.schedule = Object.freeze({
      every: (ms, handler) => call({ method: 'every', ms, handler }),
      at: (when, handler) =>
        call({
          method: 'at',
          at: when instanceof Date ? when.getTime() : when,
          handler,
        }),
      cancel: () => call({ method: 'cancel' }),
    })
  }
  return Object.freeze(stubs)
}

export class ${facetWrapperEntrypoint} extends DurableObject {
  constructor(ctx, env) {
    super(ctx, env)
    // Every method awaits \`run\`; blocking concurrency on it in the constructor
    // instead deadlocks the facet's first RPC under workerd.
    this.run = this.start()
    this.run.catch(() => {})
  }

  async start() {
    let plugin
    try {
      plugin = await import('./${pluginModule}')
    } catch (error) {
      throw new Tagged(error && error.name === 'SyntaxError' ? 'parse' : 'load', error)
    }
    if (typeof plugin.default !== 'function') {
      throw new Tagged(
        'load',
        new Error('plugin source must export a default setup function'),
      )
    }
    try {
      await plugin.default({
        id: this.ctx.props.instanceId,
        options: this.ctx.props.options,
        stubs: stubsFrom(this.ctx, this.env),
      })
    } catch (error) {
      throw new Tagged('setup', error)
    }
    return { plugin }
  }

  async setup() {
    try {
      await this.run
      return { ok: true }
    } catch (error) {
      return error instanceof Tagged ? error.result : failed('setup', error)
    }
  }

  async call(name, input) {
    let plugin
    try {
      ;({ plugin } = await this.run)
    } catch (error) {
      return error instanceof Tagged ? error.result : failed('setup', error)
    }
    const handler = plugin[name]
    if (typeof handler !== 'function') {
      return failed(
        'call',
        new Error('plugin source has no export named "' + name + '"'),
      )
    }
    try {
      return { ok: true, value: await handler(input) }
    } catch (error) {
      return failed('call', error)
    }
  }

}
`
}
