/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as HostileRouteImport } from './routes/hostile'
import { Route as PairRouteImport } from './routes/pair'
import { Route as TableRouteImport } from './routes/table'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ApiComposeFollowRouteImport } from './routes/api.compose.follow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const HostileRoute = HostileRouteImport.update({
  id: '/hostile',
  path: '/hostile',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposeFollowRoute = ApiComposeFollowRouteImport.update({
  id: '/api/compose/follow',
  path: '/api/compose/follow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/currency': typeof CurrencyRoute
  '/digest': typeof DigestRoute
  '/hostile': typeof HostileRoute
  '/pair': typeof PairRoute
  '/table': typeof TableRoute
  '/tenants': typeof TenantsRoute
  '/todo': typeof TodoRoute
  '/upgrade': typeof UpgradeRoute
  '/api/compose/follow': typeof ApiComposeFollowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/currency': typeof CurrencyRoute
  '/digest': typeof DigestRoute
  '/hostile': typeof HostileRoute
  '/pair': typeof PairRoute
  '/table': typeof TableRoute
  '/tenants': typeof TenantsRoute
  '/todo': typeof TodoRoute
  '/upgrade': typeof UpgradeRoute
  '/api/compose/follow': typeof ApiComposeFollowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/currency': typeof CurrencyRoute
  '/digest': typeof DigestRoute
  '/hostile': typeof HostileRoute
  '/pair': typeof PairRoute
  '/table': typeof TableRoute
  '/tenants': typeof TenantsRoute
  '/todo': typeof TodoRoute
  '/upgrade': typeof UpgradeRoute
  '/api/compose/follow': typeof ApiComposeFollowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/currency'
    | '/digest'
    | '/hostile'
    | '/pair'
    | '/table'
    | '/tenants'
    | '/todo'
    | '/upgrade'
    | '/api/compose/follow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/currency'
    | '/digest'
    | '/hostile'
    | '/pair'
    | '/table'
    | '/tenants'
    | '/todo'
    | '/upgrade'
    | '/api/compose/follow'
  id:
    | '__root__'
    | '/'
    | '/currency'
    | '/digest'
    | '/hostile'
    | '/pair'
    | '/table'
    | '/tenants'
    | '/todo'
    | '/upgrade'
    | '/api/compose/follow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CurrencyRoute: typeof CurrencyRoute
  DigestRoute: typeof DigestRoute
  HostileRoute: typeof HostileRoute
  PairRoute: typeof PairRoute
  TableRoute: typeof TableRoute
  TenantsRoute: typeof TenantsRoute
  TodoRoute: typeof TodoRoute
  UpgradeRoute: typeof UpgradeRoute
  ApiComposeFollowRoute: typeof ApiComposeFollowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostile': {
      id: '/hostile'
      path: '/hostile'
      fullPath: '/hostile'
      preLoaderRoute: typeof HostileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compose/follow': {
      id: '/api/compose/follow'
      path: '/api/compose/follow'
      fullPath: '/api/compose/follow'
      preLoaderRoute: typeof ApiComposeFollowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CurrencyRoute: CurrencyRoute,
  DigestRoute: DigestRoute,
  HostileRoute: HostileRoute,
  PairRoute: PairRoute,
  TableRoute: TableRoute,
  TenantsRoute: TenantsRoute,
  TodoRoute: TodoRoute,
  UpgradeRoute: UpgradeRoute,
  ApiComposeFollowRoute: ApiComposeFollowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
