// Regenerate `src/generated/lib.ts` from the installed TypeScript's own
// declaration library:
//
//     node scripts/generate-lib.mjs
//
// The checker carries the library text with it rather than reading it from disk
// so that the same declarations are used in every runtime — Node, Bun, a
// browser — and so a written plugin gets the same answer wherever the client
// happens to be running. `lib.es2022.d.ts` and everything it references, and
// nothing else: no DOM, no Node types.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const entry = 'lib.es2022.d.ts'
const here = dirname(fileURLToPath(import.meta.url))
const require = createRequire(join(here, 'generate-lib.mjs'))
const libraryDir = dirname(require.resolve('typescript'))

/** @type {Record<string, string>} */
const files = {}
const collect = (name) => {
  if (files[name] !== undefined) return
  const text = readFileSync(join(libraryDir, name), 'utf8')
  files[name] = text
  const reference = /\/\/\/\s*<reference\s+lib="([^"]+)"\s*\/>/g
  let match
  while ((match = reference.exec(text)) !== null) {
    collect(`lib.${match[1]}.d.ts`)
  }
}
collect(entry)

const version = JSON.parse(
  readFileSync(join(libraryDir, '../package.json'), 'utf8'),
).version

const banner = `/* eslint-disable */
// Generated by scripts/generate-lib.mjs from typescript@${version}. Do not edit.
// The \`${entry}\` declaration library and everything it references: the
// ambient environment a written plugin is checked against.

/** The declaration library files, by name, that the checker compiles against. */
export const declarationLibrary: Record<string, string> = JSON.parse(
`

const source = `${banner}  ${JSON.stringify(JSON.stringify(files))},\n)\n\n/** The entry point of {@link declarationLibrary}. */\nexport const declarationLibraryEntry = ${JSON.stringify(entry)}\n`

mkdirSync(join(here, '../src/generated'), { recursive: true })
writeFileSync(join(here, '../src/generated/lib.ts'), source)
console.log(
  `wrote src/generated/lib.ts — ${Object.keys(files).length} files, ${source.length} bytes`,
)
